spring:
  application:
    name: Teamply
#  profiles:
#    active: local
#
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3307/teamply_db
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

aws:
  region: ap-northeast-2
  s3:
    bucket: teamply-files-dev
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}

jwt:
  secret: teamply-super-secret-key-please-change-this-to-a-long-random-string-at-least-32-bytes
  access-token-expiration: 1800000
  refresh-token-expiration: 1209600000

gemini:
  api:
    key: ${GEMINI_API_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  access-token-expiration: 1800000
  refresh-token-expiration: 1209600000